### ISSUE TITLE
Contribute & License

### ISSUE THREAD

**Issue by nikgraf** [Ragnaroek/mithril#1]
I found your lib and would be happy to contribute the Skein and JH hash.

The reason I'm looking into it is for a side-project which is closed source. Specifically compiling a Monero miner to WebAssembly (more stuff needs to change e.g. asm is not supported for the wasm target. I would prefer to use Rust, but the overall side-project project is closed source. Here is my question: Would you consider a different license or do you want keep GPL3?

**Comment by Ragnaroek** [comment]
Using GPL3 (or GPL) is very important for me. I actually want to avoid scenarios where the code is used for closed source projects. So it is very unlikely that I will change the licence or dual licence the code with a more "foregiving" licence.

But contributing Skein/JH would still be possible. You can use a licence you choose or contribute it to https://github.com/RustCrypto/hashes?

**Comment by nikgraf** [comment]
Makes sense! Thanks for the quick response 👏

Yep, once I build a miner in Rust I will 🙂. Considering this is an experiment I will focus on compiling the C CryptoNight code first and eventually do a rewrite in Rust in the long run.
