### ISSUE TITLE
Compiling on Windows 

### ISSUE THREAD

**Issue by GasGeverij** [Ragnaroek/mithril#11]
mithril-master>cargo build --release
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading serde_derive v1.0.27
 Downloading blake v2.0.0
 Downloading env_logger v0.4.3
 Downloading config v0.7.1
 Downloading skein-ffi v0.0.1
 Downloading jh-ffi v0.0.2
 Downloading bandit v0.11.1
 Downloading groestl v0.3.0
 Downloading syn v0.11.11
 Downloading quote v0.3.15
 Downloading serde_derive_internals v0.19.0
 Downloading unicode-xid v0.0.4
 Downloading synom v0.11.3
 Downloading gcc v0.3.54
 Downloading serde-hjson v0.8.1
 Downloading yaml-rust v0.3.5
 Downloading nom v3.2.1
 Downloading toml v0.4.5
 Downloading serde v0.8.23
 Downloading regex v0.1.80
 Downloading linked-hash-map v0.3.0
 Downloading num-traits v0.1.43
 Downloading aho-corasick v0.5.3
 Downloading thread_local v0.2.7
 Downloading utf8-ranges v0.1.3
 Downloading regex-syntax v0.3.9
 Downloading memchr v0.1.11
 Downloading thread-id v2.0.0
 Downloading serde_test v0.8.23
 Downloading memchr v1.0.2
 Downloading block-buffer v0.2.0
 Downloading generic-array v0.8.3
 Downloading byte-tools v0.2.0
 Downloading digest v0.6.2
 Downloading typenum v1.9.0
 Downloading winapi-x86_64-pc-windows-gnu v0.4.0
   Compiling winapi-build v0.1.1
   Compiling winapi v0.2.8
   Compiling winapi-x86_64-pc-windows-gnu v0.4.0
   Compiling libc v0.2.39
   Compiling unicode-xid v0.0.4
   Compiling typenum v1.9.0
   Compiling void v1.0.2
   Compiling winapi v0.3.4
   Compiling serde v0.8.23
   Compiling quote v0.3.15
   Compiling nodrop v0.1.12
   Compiling gcc v0.3.54
   Compiling lazy_static v1.0.0
   Compiling utf8-ranges v0.1.3
   Compiling num-traits v0.2.1
   Compiling ucd-util v0.1.1
   Compiling regex-syntax v0.3.9
   Compiling cfg-if v0.1.2
   Compiling serde v1.0.27
   Compiling byte-tools v0.2.0
   Compiling lazy_static v0.2.11
   Compiling dtoa v0.4.2
   Compiling utf8-ranges v1.0.0
   Compiling itoa v0.3.4
   Compiling yaml-rust v0.3.5
   Compiling unreachable v1.0.0
   Compiling memchr v0.1.11
   Compiling memchr v2.0.1
   Compiling memchr v1.0.2
   Compiling num_cpus v1.8.0
   Compiling synom v0.11.3
   Compiling kernel32-sys v0.2.2
   Compiling regex-syntax v0.5.0
   Compiling log v0.4.1
   Compiling num-traits v0.1.43
   Compiling blake v2.0.0
   Compiling jh-ffi v0.0.2
   Compiling skein-ffi v0.0.1
   Compiling thread_local v0.3.5
   Compiling serde_test v0.8.23
   Compiling aho-corasick v0.5.3
   Compiling nom v3.2.1
   Compiling aho-corasick v0.6.4
   Compiling syn v0.11.11
   Compiling log v0.3.9
error: failed to run custom build command for `blake v2.0.0`
process didn't exit successfully: `C:\Users\GasGeverij\Documents\Mining\mithril-master\target\release\build\blake-a6e7c5891afef641\build-scr
ipt-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-pc-windows-gnu")
OPT_LEVEL = Some("3")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
HOST_CC = None
CC = None
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("false")
running: "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-Wall" "-Wextra" "-o" "C:\\Users\\GasGeverij\\Documents\\Mining\\mit
hril-master\\target\\release\\build\\blake-d7c992cdce3efa2c\\out\\ext/blake\\blake_ref.o" "-c" "ext/blake/blake_ref.c"

--- stderr
thread 'main' panicked at '

Internal error occurred: Failed to find tool. Is `gcc.exe` installed? (see https://github.com/alexcrichton/gcc-rs#compile-time-requirements f
or help)

', C:\Users\GasGeverij\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.54\src\lib.rs:1670:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

rustc --version
rustc 1.26.0-nightly (75af15ee6 2018-03-20)

**Comment by Ragnaroek** [comment]
Hi,
did you check-out the link: https://github.com/alexcrichton/gcc-rs#compile-time-requirements ?

Looks like gcc is not installed on your windows?

**Comment by GasGeverij** [comment]
Yeah, i was just looking at that haha we can close this.
Also sent you an email btw, great project :)
