### ISSUE TITLE
gcc problem ?

### ISSUE THREAD

**Issue by GasGeverij** [Ragnaroek/mithril#12]
Hi, again i installed gcc but i think i'm still missing something 

C:\Users\GasGeverij\Documents\Mining\mithril-master>cargo build --release
   Compiling blake v2.0.0
   Compiling jh-ffi v0.0.2
   Compiling skein-ffi v0.0.1
   Compiling thread_local v0.2.7
   Compiling groestl v0.3.0
   Compiling bandit v0.11.1
error: failed to run custom build command for `jh-ffi v0.0.2`
process didn't exit successfully: `C:\Users\GasGeverij\Documents\Mining\mithril-master\target\release\build\jh-ffi-71c4f16816cc3dda\build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-pc-windows-gnu")
OPT_LEVEL = Some("3")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
HOST_CC = None
CC = None
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("false")
running: "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-Wall" "-Wextra" "-o" "C:\\Users\\GasGeverij\\Documents\\Mining\\mithril-master\\target\\release\\build\\jh-ffi-93b7ffe38715e165\\out\\
ext/jh\\c_jh.o" "-c" "ext/jh/c_jh.c"
cargo:warning=ext/jh/c_jh.c:1:0: sorry, unimplemented: 64-bit mode not compiled in
cargo:warning= /*This program gives the 64-bit optimized bitslice implementation of JH using ANSI C
cargo:warning=
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-Wall" "-Wextra" "-o" "C:\\Users\\GasGeverij\\Documents\\Mining\\mithril-master\\target\\release\\build\\jh-ffi
-93b7ffe38715e165\\out\\ext/jh\\c_jh.o" "-c" "ext/jh/c_jh.c" with args "gcc.exe" did not execute successfully (status code exit code: 1).

', C:\Users\GasGeverij\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.54\src\lib.rs:1670:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `skein-ffi v0.0.1`
process didn't exit successfully: `C:\Users\GasGeverij\Documents\Mining\mithril-master\target\release\build\skein-ffi-fb62bf4d353dbb57\build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-pc-windows-gnu")
OPT_LEVEL = Some("3")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
HOST_CC = None
CC = None
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("false")
running: "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-Wall" "-Wextra" "-o" "C:\\Users\\GasGeverij\\Documents\\Mining\\mithril-master\\target\\release\\build\\skein-ffi-4397f3446073ef62\\ou
t\\ext/skein\\c_skein.o" "-c" "ext/skein/c_skein.c"
cargo:warning=ext/skein/c_skein.c:1:0: sorry, unimplemented: 64-bit mode not compiled in
cargo:warning= /***********************************************************************
cargo:warning=
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-Wall" "-Wextra" "-o" "C:\\Users\\GasGeverij\\Documents\\Mining\\mithril-master\\target\\release\\build\\skein-
ffi-4397f3446073ef62\\out\\ext/skein\\c_skein.o" "-c" "ext/skein/c_skein.c" with args "gcc.exe" did not execute successfully (status code exit code: 1).

', C:\Users\GasGeverij\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.54\src\lib.rs:1670:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `blake v2.0.0`
process didn't exit successfully: `C:\Users\GasGeverij\Documents\Mining\mithril-master\target\release\build\blake-a6e7c5891afef641\build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-pc-windows-gnu")
OPT_LEVEL = Some("3")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
HOST_CC = None
CC = None
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("false")
running: "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-Wall" "-Wextra" "-o" "C:\\Users\\GasGeverij\\Documents\\Mining\\mithril-master\\target\\release\\build\\blake-d7c992cdce3efa2c\\out\\e
xt/blake\\blake_ref.o" "-c" "ext/blake/blake_ref.c"
cargo:warning=ext/blake/blake_ref.c:1:0: sorry, unimplemented: 64-bit mode not compiled in
cargo:warning= #include <string.h>
cargo:warning=
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-Wall" "-Wextra" "-o" "C:\\Users\\GasGeverij\\Documents\\Mining\\mithril-master\\target\\release\\build\\blake-
d7c992cdce3efa2c\\out\\ext/blake\\blake_ref.o" "-c" "ext/blake/blake_ref.c" with args "gcc.exe" did not execute successfully (status code exit code: 1).

', C:\Users\GasGeverij\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.54\src\lib.rs:1670:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by Ragnaroek** [comment]
Did you solve it? Can you share if yes?
