### ISSUE TITLE
MacOS: Config file not found error

### ISSUE THREAD

**Issue by dennisfurrer** [Ragnaroek/mithril#18]
In the Mithril dir I copied the default_config.toml file and renamed it to config.toml. I also made the required changes to the config.toml file (e.g. address). I then run "cargo build --release" and navigate to /target/release and run the "mithril" executable. I get the following output:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: config file not found', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by Ragnaroek** [comment]
Hi.

the config file has to be in the current working directory. If you 'cd' into target/release and start the executable from there the config file has to be in this folder.
If you are in the mithril folder and start the executable with ./target/release/mithril it should work with the config file in the default location.

**Comment by dennisfurrer** [comment]
Hi, thank you but now I get the following error message:

thread 'metric sample thread' panicked at 'overflow converting duration to nanoseconds', libcore/option.rs:960:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by Ragnaroek** [comment]
Hi,
you are now running into the same problem as in issues https://github.com/Ragnaroek/mithril/issues/17

Should be fixed in version 0.10.0. Can you try it out and report back if it is working/not working?

**Comment by dennisfurrer** [comment]
Perfect, thanks 👍
