### ISSUE TITLE
MacBook Pro 2018 6-core i7 when running "cargo build --release"

### ISSUE THREAD

**Issue by dennisfurrer** [Ragnaroek/mithril#19]
fi-0.0.1/src/lib.rs:2:1
  |
2 | #![feature(libc)]
  | ^^^^^^^^^^^^^^^^^

error[E0554]: #![feature] may not be used on the stable release channel

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: Could not compile `skein-ffi`.
warning: build failed, waiting for other jobs to finish...
error: Could not compile `jh-ffi`.

To learn more, run the command again with --verbose.

**Comment by Ragnaroek** [comment]
Hi Dennis,

you need to use the nightly version of Rust, mainly because mithril uses inline assembler, which is not yet available in the stable version.

Try `rustup install nightly` and compile it again with the nightly version.

**Comment by dennisfurrer** [comment]
Hi, I tried that however it gives me the same message

**Comment by Ragnaroek** [comment]
can you post what `rustup show` prints?
