### ISSUE TITLE
Specify build requirements in the readme

### ISSUE THREAD

**Issue by Susurrus** [Ragnaroek/mithril#2]
Really excited that you're building a miner in Rust. I'm interested in helping test and develop. I'm currently just trying to build it and run it on my local machine on the CPU, but ran into a problem compiling as it appears this requires a nightly. It would be helpful to have this (and any other needs) documented in the README.

**Comment by Susurrus** [comment]
Also found that to run it you need to copy the `default_config.toml` to `config.toml`.

**Comment by Ragnaroek** [comment]
Thanks for testing it :) I was focusing completely on the implementation. But now that is fully working I will add some more information to the README how to run it.

**Comment by Ragnaroek** [comment]
added a short documentation, closing issue.
