### ISSUE TITLE
Possible to add more Alt-coin algorithm to this project?

### ISSUE THREAD

**Issue by sequencer** [Ragnaroek/mithril#20]
Hello, I wonder is it possible to split your project into different modules, so that we can reuse more code.
I wanna adder SHA256d, X11 etc algorithms.
And also as for the algorithm backend, I also wanna implement some protocol and use it for ASIC miner.

**Comment by Ragnaroek** [comment]
Sure, if you make a proposal I can extract a module for some parts.

Regarding Alt-coins: I'm not super interested in them, but would add a PR for adding some Monero variants to the project.

**Comment by sequencer** [comment]
thank you!
I'm going to read more about your code ;)

**Comment by calidion** [comment]
What is the progress?
Can it be used to mine the origin cryptonight alt coins?

**Comment by calidion** [comment]
Extracted cryptonight into  cargo `cryptonight = "0.1.0"`.

thank you. Hope pure rust version will be implemented soon.

@Ragnaroek

**Comment by Ragnaroek** [comment]
Hi,
I currently do not have the time to add altcoins to mithril, but would welcome PR for that!
Extracting the cryptonight core is great! I hope somebody finds it useful.
