### ISSUE TITLE
Use of depricated function within a library

### ISSUE THREAD

**Issue by Thanathotius** [Ragnaroek/mithril#23]
Currently, mithril uses a depricated function which is the Select in:

use std::sync::mpsc::{channel, Sender, Receiver, RecvTimeoutError, Select};

`error[E0432]: unresolved import `std::sync::mpsc::Select`
 --> src\metric\mod.rs:3:68
  |
3 | use std::sync::mpsc::{channel, Sender, Receiver, RecvTimeoutError, Select};
  |                                                                    ^^^^^^ no `Select` in `sync::mpsc`
`

Is there a plan of when this is going to be redone? I imagine it's quite a lot of work to redo it but I still feel like it should be pointed out that the usage of this Select function is not in the library anymore.

**Comment by Ragnaroek** [comment]
Yes, Select was removed from Rust some time ago. There are plans to rework this, but not so soon. Also a update to the latest Monero version would be needed.

**Comment by moriartydev** [comment]
This error prevents me from building the project, any variants to solve it?

**Comment by Ragnaroek** [comment]
replace the deprecated mpsc channel with crossbeam
