### ISSUE TITLE
Questions regarding this project.

### ISSUE THREAD

**Issue by Joe23232** [Ragnaroek/mithril#27]
Hi I have some questions regarding this project:
1. Is it workable right now? Am I able to generate hashes to earn money?
2. Can I control how much processing power to take to generate hashes?
3. Am I able to change the output or not even display a console session for situations I may not want a console to open and for it to run in the background?
4. Say if I have a Monera wallet stored on my computer A and it is off, and I am doing cryptomining (using this crate) on Computer B and Computer B does NOT store the wallet and I wanted to send it off. Do I need to store the wallet on a server? Does Monera have a server where I can chose to create a wallet and where all my money can go over there?
5. Is this crate capable of sending generated hashes via the Internet?

**Comment by Ragnaroek** [comment]
> Hi I have some questions regarding this project:
> 
>     1. Is it workable right now? Am I able to generate hashes to earn money?
> 
It works. Although pretty slow at the moment. It is not a good idea to use it for any commercial purposes at the moment. Optimisation is ongoing in this project.

>     2. Can I control how much processing power to take to generate hashes?
> 
You can configure the amounts of threads mithril uses.

>     3. Am I able to change the output or not even display a console session for situations I may not want a console to open and for it to run in the background?

You can wrap a custom script around the binary call to customize the output for your needs. There is no configuration possible beyond the output file path and the LOG_LEVEL at the moment.

> 
>     4. Say if I have a Monera wallet stored on my computer A and it is off, and I am doing cryptomining (using this crate) on Computer B and Computer B does NOT store the wallet and I wanted to send it off. Do I need to store the wallet on a server? Does Monera have a server where I can chose to create a wallet and where all my money can go over there?
> 

Mithril is purely for (pool) mining. It has no wallet feature.

>     5. Is this crate capable of sending generated hashes via the Internet?

It can only do that. Only pool mining is supported at the moment. Solo mining will maybe come in the future.

**Comment by Joe23232** [comment]
Hey mate.

> It works. Although pretty slow at the moment. It is not a good idea to use it for any commercial purposes at the moment. Optimisation is ongoing in this project.

I thought this code is just a wrapper or something to a pre-existing API?

Also how many people are working on this project just out of curiosity?

> You can configure the amounts of threads mithril uses.

And can I slow it down so it doesn't take too much of my performance?

> You can wrap a custom script around the binary call to customize the output for your needs. There is no configuration possible beyond the output file path and the LOG_LEVEL at the moment.

Right I see thanks.

> Mithril is purely for (pool) mining. It has no wallet feature.

Yes I understand that, but like the money is going to go into a wallet, can I have a centralised wallet where it is stored on a server rather than on my device?

> It can only do that. Only pool mining is supported at the moment. Solo mining will maybe come in the future.

Pool mining means like multiple mining together, right?

**Comment by Ragnaroek** [comment]
> Hey mate.
> 
> > It works. Although pretty slow at the moment. It is not a good idea to use it for any commercial purposes at the moment. Optimisation is ongoing in this project.
> 
> I thought this code is just a wrapper or something to a pre-existing API?
> 

No, it's "original" work and a native RandomX implementation in Rust :)


> Also how many people are working on this project just out of curiosity?
>
Just me, a.t.m
 
> > You can configure the amounts of threads mithril uses.
> 
> And can I slow it down so it doesn't take too much of my performance?
> 
Only by how many threads are used. If you configure < core count there should be room for other stuff.


> > You can wrap a custom script around the binary call to customize the output for your needs. There is no configuration possible beyond the output file path and the LOG_LEVEL at the moment.
> 
> Right I see thanks.
> 
> > Mithril is purely for (pool) mining. It has no wallet feature.
> 
> Yes I understand that, but like the money is going to go into a wallet, can I have a centralised wallet where it is stored on a server rather than on my device?
> 
> > It can only do that. Only pool mining is supported at the moment. Solo mining will maybe come in the future.
> 
> Pool mining means like multiple mining together, right?

I think both questions belong together. Mithril can a.t.m only used with pool mining. If a block is found the reward is distributed relational too much you mined towards that block. Payment is than automatically done by the pool to the address you configured for mining.

**Comment by Joe23232** [comment]
How many people are contributing to this project?

> I think both questions belong together. Mithril can a.t.m only used with pool mining. If a block is found the reward is distributed relational too much you mined towards that block. Payment is than automatically done by the pool to the address you configured for mining.

So lets just say I configured three of my computers to do pool mining, and two of my computers were offline but only one of them was online. Can they still continue to mine or would they be put on "hold" or something?

**Comment by Ragnaroek** [comment]
If they are offline they cannot mine. They need a more or less constant connection to the mining pool and receive new 'jobs'. They also need to transmit shares in a timely manner to the pool so that they count as valid. I thinks this is a good introduction into pool mining: https://en.wikipedia.org/wiki/Mining_pool

**Comment by Joe23232** [comment]
Right I see, thanks

**Comment by mirkoRainer** [comment]
Hello. Just continuing here instead of opening a new issue.

How beginner friendly are the open issues/features? I haven't done anything serious with Rust but am looking to start on something.
