### ISSUE TITLE
Is this program designed so I can import it as a crate?

### ISSUE THREAD

**Issue by Joe23232** [Ragnaroek/mithril#28]
Hi I have a question, am I able to use this as a crate and use all the high level cryptomining features? That way I can integrate it into my Rust GUI Software which can then allow the user to control the options with a GUI interface?

**Comment by Ragnaroek** [comment]
I currently have no plans to release mithril as a library (but nothing speaks against that per se). You could also start the binary from GUI and control the program through the config file.

**Comment by Joe23232** [comment]
I see thanks

**Comment by cryptoquick** [comment]
FWIW, I'd like to see an embeddable version of this published, also.
