### ISSUE TITLE
Why the old rust edition?

### ISSUE THREAD

**Issue by max-ishere** [Ragnaroek/mithril#32]
This crate does not define a rust edition and uses older syntax. Is there a reason for this or it is not important?

**Comment by Gonert** [comment]
Rust evolves so much and over such short amounts of time that it is normal for code bases to look like they look older syntax, in a perfect world it could be kept up to date with newest practices but sometimes that is not practical and maybe not even needed as it wouldn't change the performace enough to worry about it. In the end it's not entirely important/

**Comment by Ragnaroek** [comment]
The project was started a while ago and it is not really active at the moment. I don't maintain it to keep up with the latest rust updates t.b.h.
