### ISSUE TITLE
Hashrate issues

### ISSUE THREAD

**Issue by emmalaporte93** [Ragnaroek/mithril#34]
Hi  @Ragnaroek! I was testing  mithril today with x86_64-pc-windows-gnu/x86_64-pc-windows-gnu  toolchains , and it seems its way too (~50 times) slower than xmrig on RandomX; maybe I'm doing something wrong? :) My expectation was that its 2-3 times slower than xmrig

**Comment by Ragnaroek** [comment]
50 times slower is surprising. If you let it run with auto-tuning, the bandit algorithm needs some time to find the optimal settings. Alas I cannot say howlong it will take.
