### ISSUE TITLE
Naive questions, is possible to port to webassembbly?

### ISSUE THREAD

**Issue by eugenioclrc** [Ragnaroek/mithril#35]
Wonder if this could run in a browser using webassembbly.

**Comment by Ragnaroek** [comment]
This would be possible, at least two things have to be changed for this:
- The threading code has to be replaced with async code, as there are no thread available (yet?) in webassembly. I think this would be the major work.
- There is also some x86 assembler code that needs to re-written in pure rust or webassembly.

But with that tackled it should be possible. Currently working on a project that support webassembly and it was suprisingly easy to support web: https://github.com/Ragnaroek/iron-wolf/
