### ISSUE TITLE
Specify what is logged by the log file

### ISSUE THREAD

**Issue by Susurrus** [Ragnaroek/mithril#6]
`default_config.txt` talks about logging to a file. I was sure what would be logged, but since there isn't a way to see the hash rate, that it would output a hashrate. Now I'm seeing a log file that looks like:
```
1514864820053;4729
1514864880053;5055
1514864940053;5489
1514865000054;5349
1514865060054;5835
```

I see the first one is a timestamp, but what's the second number? It'd be great if the logging was better documented.

**Comment by Ragnaroek** [comment]
Hi Bryant,

I clarified the format a little bit in the README. I hope this makes the format for the hash-rate logging very clear. If yes, please close this issue. If no, give me feedback :)

**Comment by Susurrus** [comment]
Awesome, thanks!
