### ISSUE TITLE
jh-ffi error

### ISSUE THREAD

**Issue by ianchov** [Ragnaroek/mithril#8]
Strangely i installed with rust-up the nighly but i see stable channel..any ideas why not compile?

# cargo build --release
   Compiling skein-ffi v0.0.1
   Compiling jh-ffi v0.0.2
   Compiling serde_derive v1.0.27
   Compiling env_logger v0.4.3
error[E0554]: #![feature] may not be used on the stable release channel
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/skein-ffi-0.0.1/src/lib.rs:2:1
  |
2 | #![feature(libc)]
  | ^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error[E0554]: #![feature] may not be used on the stable release channel
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/jh-ffi-0.0.2/src/lib.rs:2:1
  |
2 | #![feature(libc)]
  | ^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `jh-ffi`.
warning: build failed, waiting for other jobs to finish...
The following warnings were emitted during compilation:

warning: ext/skein/c_skein.c: In function ‘Skein_256_Final’:
warning: ext/skein/c_skein.c:1360:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning: ext/skein/c_skein.c: In function ‘Skein_512_Final’:
warning: ext/skein/c_skein.c:1560:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning: ext/skein/c_skein.c: In function ‘Skein1024_Final’:
warning: ext/skein/c_skein.c:1758:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

error: Could not compile `skein-ffi`.
warning: build failed, waiting for other jobs to finish...

**Comment by ianchov** [comment]
`# cargo build --release
   Compiling skein-ffi v0.0.1
   Compiling jh-ffi v0.0.2
   Compiling serde_derive v1.0.27
   Compiling env_logger v0.4.3
error[E0554]: #![feature] may not be used on the stable release channel
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/skein-ffi-0.0.1/src/lib.rs:2:1
  |
2 | #![feature(libc)]
  | ^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error[E0554]: #![feature] may not be used on the stable release channel
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/jh-ffi-0.0.2/src/lib.rs:2:1
  |
2 | #![feature(libc)]
  | ^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `jh-ffi`.
warning: build failed, waiting for other jobs to finish...
The following warnings were emitted during compilation:

warning: ext/skein/c_skein.c: In function ‘Skein_256_Final’:
warning: ext/skein/c_skein.c:1360:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning: ext/skein/c_skein.c: In function ‘Skein_512_Final’:
warning: ext/skein/c_skein.c:1560:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning: ext/skein/c_skein.c: In function ‘Skein1024_Final’:
warning: ext/skein/c_skein.c:1758:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

error: Could not compile `skein-ffi`.
warning: build failed, waiting for other jobs to finish...
`

**Comment by ianchov** [comment]
#![feature(libc)

**Comment by ianchov** [comment]
I tried adding
libc = "0.1" in the Cargo.toml dependencies but still the same error

**Comment by Susurrus** [comment]
Try running it like `rustup run nightly cargo build --release`. It doesn't appear your `rustup` install has the nightly compiler as the default.

**Comment by ianchov** [comment]
You are right:
# rustup run nightly cargo build --release
error: toolchain 'nightly-x86_64-unknown-linux-gnu' is not installed


I have to make a new try

**Comment by ianchov** [comment]
Successfully compiled with nighly!

Thanks!
