### ISSUE TITLE
Windows 10 cannot find config file

### ISSUE THREAD

**Issue by ianchov** [Ragnaroek/mithril#9]
C:\Users\server\Downloads\mithril-master\mithril-master\target\release>mithril.exe
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: config file not found', src\libcore\result.rs:916:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

config.toml is in the directory

**Comment by Ragnaroek** [comment]
Did you cd into the directory C:\Users\server\Downloads\mithril-master\mithril-master\target\release and put the config.toml there. The config.toml has to be in the current working directory, which is different if you executed C:\Users\server\Downloads\mithril-master\mithril-master\target\release\mithril.exe from another path.

**Comment by ianchov** [comment]
Thanks! This time it ran!
Actually i had put config.toml in the current dir however it was config.toml.txt
